version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: ./docker/Dockerfile.local
    environment:
      DB_CONN_STRING: mongodb
      DB_CONN_PORT: 27017
    ports:
      - 8000:8000
    volumes:
      - ./server/src:/home/server/app/src
    command: npm run start:dev
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.local
    volumes:
      - ./frontend/:/frontend
    ports:
      - 5173:5173
    command: npm run dev
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db:rw
